### ISSUE TITLE
Python2.7 tests fail

### ISSUE THREAD

**Issue by jonringer** [rocky/python-xdis#51]
was bumping this package from 4.0.1 to 4.0.3, and noticed that the python tests for python2.7 fail.

system info:
```
$ python --version
Python 2.7.16
$ uname -a
Linux jon-workstation 4.19.64 #1-NixOS SMP Sun Aug 4 07:30:58 UTC 2019 x86_64 GNU/Linux
```

Failure:
```
======================================================================
FAIL: test_bug_708901 (test_dis27.DisTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/xdis-4.0.3/test_unit/test_dis27.py", line 161, in test_bug_708901
    self.do_disassembly_test(bug708901, dis_bug708901)
  File "/build/xdis-4.0.3/test_unit/test_dis27.py", line 137, in do_disassembly_test
    lines)))
AssertionError: events did not match expectation:
   19:           0 SETUP_LOOP               23 (to 26)
                 3 LOAD_GLOBAL               0 (range)
                 6 LOAD_CONST                1 (1)

   20:           9 LOAD_CONST                2 (10)
-               12 CALL_FUNCTION             2 (2 positional, 0 keyword pair)
?                                                               ^ ---- -----

+               12 CALL_FUNCTION             2 (2 positional, 0 named)
?                                                               ^^^

                15 GET_ITER
           >>   16 FOR_ITER                  6 (to 25)
                19 STORE_FAST                0 (res)

   21:          22 JUMP_ABSOLUTE            16 (to 16)
           >>   25 POP_BLOCK
           >>   26 LOAD_CONST                0 (None)
                29 RETURN_VALUE



======================================================================
FAIL: test_dis (test_dis27.DisTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/xdis-4.0.3/test_unit/test_dis27.py", line 155, in test_dis
    self.do_disassembly_test(_f, dis_f)
  File "/build/xdis-4.0.3/test_unit/test_dis27.py", line 137, in do_disassembly_test
    lines)))
AssertionError: events did not match expectation:
   30:           0 LOAD_GLOBAL               0 (print)
                 3 LOAD_FAST                 0 (a)
-                6 CALL_FUNCTION             1 (1 positional, 0 keyword pair)
?                                                               ^ ---- -----

+                6 CALL_FUNCTION             1 (1 positional, 0 named)
?                                                               ^^^

                 9 POP_TOP

   31:          10 LOAD_CONST                1 (1)
                13 RETURN_VALUE



----------------------------------------------------------------------
Ran 7 tests in 0.199s

FAILED (failures=2, skipped=1)
================ 3 failed, 11 passed, 1 skipped in 1.29 seconds ================
```

**Comment by rocky** [comment]
Ok - thanks for reporting Fixed in the master branch now. You'd help me out in the future to give not only failing output but the _command_ you issued to run that. I am assuming it was `py.test` in the root directory without parameters.

**Comment by jonringer** [comment]
that is correct, i just ran `pytest` from the root level.

**Comment by jonringer** [comment]
I should have included that, sorry :smile: . Nixpkgs is a little weird because I don't directly input anything... :). I had to change the default test phase because it looks like you were no longer exporting your pytest directory as a part of your pypi package. I would have checked out from your github repo if it wasn't for having successful tests of python3.7

That was a very fast turn around! :)

**Comment by rocky** [comment]
Ok. Thanks for the information.
