### ISSUE TITLE
key error!!!!

### ISSUE THREAD

**Issue by ahmedmoselhi** [rocky/python-xdis#65]
$ uncompyle6 -h
Traceback (most recent call last):
  File "/home/ahmedmoselhi/.local/bin/uncompyle6", line 5, in <module>
    from uncompyle6.bin.uncompile import main_bin
  File "/home/ahmedmoselhi/.local/lib/python2.7/site-packages/uncompyle6/__init__.py", line 53, in <module>
    import uncompyle6.semantics.pysource
  File "/home/ahmedmoselhi/.local/lib/python2.7/site-packages/uncompyle6/semantics/pysource.py", line 141, in <module>
    from uncompyle6.parsers.treenode import SyntaxTree
  File "/home/ahmedmoselhi/.local/lib/python2.7/site-packages/uncompyle6/parsers/treenode.py", line 3, in <module>
    from uncompyle6.scanners.tok import NoneToken
  File "/home/ahmedmoselhi/.local/lib/python2.7/site-packages/uncompyle6/scanners/tok.py", line 200, in <module>
    NoneToken = Token("LOAD_CONST", offset=-1, attr=None, pattr=None)
  File "/home/ahmedmoselhi/.local/lib/python2.7/site-packages/uncompyle6/scanners/tok.py", line 86, in __init__
    from xdis.std import _std_api
  File "/home/ahmedmoselhi/.local/lib/python2.7/site-packages/xdis/std.py", line 220, in <module>
    _std_api = make_std_api()
  File "/home/ahmedmoselhi/.local/lib/python2.7/site-packages/xdis/std.py", line 218, in make_std_api
    return _StdApi(python_version, variant)
  File "/home/ahmedmoselhi/.local/lib/python2.7/site-packages/xdis/std.py", line 73, in __init__
    self.opc = opc = get_opcode_module(python_version, variant)
  File "/home/ahmedmoselhi/.local/lib/python2.7/site-packages/xdis/op_imports.py", line 169, in get_opcode_module
    return op_imports[canonic_python_version[vers_str]]
KeyError: '2.7.18candidate1'

**Comment by licy183** [comment]
Are you using Python 2 on Ubuntu 20.04? I have the same problem. You can add this version string in the variable `op_imports` in the file `/usr/local/lib/python2.7/dist-packages/xdis/op_imports.py`. Just like this 
```py
...
2.7     : opcode_27,
'2.7.18candidate1' : opcode_27,
'3.0'   : opcode_30,
...
```
And add the version string in the file `/usr/local/lib/python2.7/dist-packages/xdis/magic.py` at line 358
```py
# "2.7.17rc1 2.7.17candidate1 2.7.17 2.7.18",
"2.7.17rc1 2.7.17candidate1 2.7.17 2.7.18 2.7.18candidate1",
```

**Comment by rocky** [comment]
@licy183 If you putt in a PR all add this. 

Normally I don't add releace candidates, but if Ubuntu 20.04 has this in its default Python, I suppose we'll add it.

**Comment by ahmedmoselhi** [comment]
> Are you using Python 2 on Ubuntu 20.04? I have the same problem. You can add this version string in the variable `op_imports` in the file `/usr/local/lib/python2.7/dist-packages/xdis/op_imports.py`. Just like this
> 
> ```python
> ...
> 2.7     : opcode_27,
> '2.7.18candidate1' : opcode_27,
> '3.0'   : opcode_30,
> ...
> ```
> 
> And add the version string in the file `/usr/local/lib/python2.7/dist-packages/xdis/magic.py` at line 358
> 
> ```python
> # "2.7.17rc1 2.7.17candidate1 2.7.17 2.7.18",
> "2.7.17rc1 2.7.17candidate1 2.7.17 2.7.18 2.7.18candidate1",
> ```

yes this fixed it .. thnx
