### ISSUE TITLE
Invalid Syntax in unmarshal.py for Python 2.7

### ISSUE THREAD

**Issue by rothi83** [rocky/python-xdis#83]
Occurs at Line 98 in unmarshal.py. Using Python2.7 on MacOs.

```
Traceback (most recent call last):
  File "/Users/****/Library/Python/2.7/bin//pydisasm", line 5, in <module>
    from xdis.bin.pydisasm import main
  File "/Users/****/Library/Python/2.7/lib/python/site-packages/xdis/__init__.py", line 73, in <module>
    from xdis.load import (
  File "/Users/****/Library/Python/2.7/lib/python/site-packages/xdis/load.py", line 22, in <module>
    import xdis.unmarshal
  File "/Users/****/Library/Python/2.7/lib/python/site-packages/xdis/unmarshal.py", line 98
    def compat_str(s: str) -> str:
                    ^
SyntaxError: invalid syntax
```

**Comment by rocky** [comment]
Install using the Python 2.7 egg, not the wheel which is improperly marked Python2.  In a future release, I'll adjust the packaging.

**Comment by rothi83** [comment]
Ok got it. Works now. Thank you very much.
